[phases.setup]
nixPkgs = ["...", "playwright-driver.browsers"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt", "python -m playwright install chromium"]

[start]
cmd = "python main.py"